name: "IaC - 001 - Apply Resources"

on:
  push:
    branches:
      - main
    paths:
      - "infra/tables/**"
      - "infra/terraform/resources/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/tables/**"
      - "infra/terraform/resources/**"
  workflow_dispatch:
    inputs:
      override:
        description: "Redeploy branch?"
        required: false
        type: boolean
        default: false
      suffix:
        description: "Suffix to identify manual deployment (madatory when not redeploying a branch):"
        required: false
        type: string

# More info:
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  id-token: write
  contents: read

env:
  # These environment variables are used by the Terraform Azure provider to setup OIDD authenticate.
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"

  # These environment variables are used by this workflow to determine the proper deployment configuration.
  DEPLOYMENT_SUFFIX: ${{ github.event_name == 'pull_request' && (github.event.pull_request.base.ref == 'main' && 'pro') || (github.event.pull_request.base.ref == 'test' && 'tst') || (github.event.pull_request.base.ref == 'develop' && 'dev') || github.event_name == 'workflow_dispatch' && inputs.suffix || (github.ref == 'refs/heads/main' && 'pro') || (github.ref == 'refs/heads/test' && 'tst') || (github.ref == 'refs/heads/develop' && 'dev') }}
  ENVIRONMENT: ${{ (github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main') && 'Production' || (github.ref == 'refs/heads/test' || github.event.pull_request.base.ref == 'test') && 'Staging' || (github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop') && 'Development' || 'Development' }}
  ENVIRONMENT_SUFFIX: ${{ (github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main') && 'pro' || (github.ref == 'refs/heads/test' || github.event.pull_request.base.ref == 'test') && 'tst' || (github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop') && 'dev' || 'dev' }}

jobs:
  validate-inputs:
    name: "Validate Inputs"
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if suffix is required
        if: ${{ inputs.override == 'false' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/develop') && !inputs.suffix }}
        run: |
          echo "Error: The input of a suffix to identify a manual deployment is required when not overriding a branch environment (i.e., 'override' is false) and the branch is not 'main', 'test', or 'develop'."
          exit 1

  resources-plan:
    name: "Plan Resources"
    needs: validate-inputs
    if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && success()) }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -upgrade -backend-config="resource_group_name=${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ vars.TF_BACKEND_CONTAINER_NAME }}" -backend-config="key=${{ env.DEPLOYMENT_SUFFIX }}.terraform.tfstate"
        working-directory: ${{ vars.TF_WORKING_DIR_RESOURCES }}

      - name: Terrraform Plan
        run: |
          terraform plan \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="use_random_suffix=false" \
            -var="suffix=${{ env.DEPLOYMENT_SUFFIX }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="resource_group_name=${{ vars.AZ_RG_NAME }}" \
            -var="acr_name=${{ vars.AZ_ACR_NAME }}" \
            -var="aca_bot_name=${{ vars.AZ_ACA_BOT_NAME }}" \
            -var="aca_ai_assistant_name=${{ vars.AZ_ACA_AI_ASSISTANT_NAME }}" \
            -var="aca_ai_agent_chitchat_name=${{ vars.AZ_ACA_AI_AGENT_CHITCHAT_NAME }}" \
            -var="aca_ai_agent_companydocs_name=${{ vars.AZ_ACA_AI_AGENT_COMPANYDOCS_NAME }}" \
            -var="aca_ai_agent_ask_name=${{ vars.AZ_ACA_AI_AGENT_ASK_NAME }}" \
            -var="aca_ai_agent_summarize_name=${{ vars.AZ_ACA_AI_AGENT_SUMMARIZE_NAME }}" \
            -var="aca_ai_agent_translate_name=${{ vars.AZ_ACA_AI_AGENT_TRANSLATE_NAME }}" \
            -var="aais_endpoint=${{ vars.AZ_AI_SEARCH_ENDPOINT }}" \
            -var="aais_key=${{ secrets.AZ_AI_SEARCH_KEY }}" \
            -var="sharepoint_app_client_secret=${{ secrets.APP_SHAREPOINT_SECRET }}" \
            -var="afunc_sharepoint_document_picker_name=${{ vars.AZ_FUNC_SHAREPOINT_DOC_PICKER_NAME }}" \
            -var="afunc_sharepoint_document_proccessor_name=${{ vars.AZ_FUNC_SHAREPOINT_DOC_PROCCESSOR_NAME }}" \
            -var="afunc_document_picker_name=${{ vars.AZ_FUNC_DOC_PICKER_NAME }}" \
            -var="sharepoint_app_tenant_id=${{ secrets.APP_SHAREPOINT_TENANT }}" \
            -var="sharepoint_app_client_id=${{ secrets.APP_SHAREPOINT_CLIENT }}" \
            -var="sharepoint_app_tenant_url=${{ vars.SHAREPOINT_DOMAIN }}" \
            -var="sharepoint_app_site_relative_url=${{ vars.SHAREPOINT_FOLDER }}" \
            -var="sharepoint_app_checkifexists=${{ vars.FUNC_CHECK_DOCS }}" \
            -var="afunc_service_plan_name=${{ vars.AZ_FUNC_SERVICE_PLAN_NAME }}" \
            -detailed-exitcode \
            -out=tfplan
        working-directory: ${{ vars.TF_WORKING_DIR_RESOURCES }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          overwrite: true
          path: ${{ vars.TF_WORKING_DIR_RESOURCES }}/tfplan

  # Apply the Terraform plan only if the event is not a pull request, to prevent unapproved changes to the infrastructure.
  # Due to a bug in GitHub Actions, the `if` condition ensures that this job always runs, but only if the "resources-plan" jobs succeeded and the event is not a pull request.
  # References:
  # - https://github.com/actions/runner/issues/2205
  # - https://github.com/orgs/community/discussions/45058
  resources-apply:
    name: "Apply Resources"
    needs: resources-plan
    if: ${{  always() && needs.resources-plan.result == 'success' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ vars.TF_WORKING_DIR_RESOURCES }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -upgrade -backend-config="resource_group_name=${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ vars.TF_BACKEND_CONTAINER_NAME }}" -backend-config="key=${{ env.DEPLOYMENT_SUFFIX }}.terraform.tfstate"
        working-directory: ${{ vars.TF_WORKING_DIR_RESOURCES }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ vars.TF_WORKING_DIR_RESOURCES }}
